default: &default
  pool: 10
  encoding: unicode
  host: localhost
  username: admin
  password: n1i2c3iQQ
  adapter: postgresql

development:
  <<: *default
  database: article_language_development

test:
  <<: *default
  database: article_language_test

production:
  <<: *default
  database: article_language_production